# docker环境
spring:
  thymeleaf:
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: springcloud
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    custom:
      appid: 9A064E7A180BB4790F827F546F699BB3
      exchange: synch-exchange
      routingkey: synch-routing
liumapp:
  filemanager:
    savePath: /spring-cloud-digital-sign/data/source-file/

